#!/bin/bash

######### Configs #########
hostname='new-hostname';
interface='eth0';
####### End configs #######


txtoc="\e[0m"; # oc
txtred="\e[31m"; # red
txtgrn="\e[38;2;0;230;153m"; # green


echo -e "${txtgrn}===============================";
echo -e "${txtgrn}hostnamectl\n${txtoc}";
hostnamectl set-hostname $hostname;
hostnamectl;
echo '';
echo -e "${txtgrn}===============================";
echo -e "${txtgrn}change_hostname.py\n${txtoc}";
change_hosts.py $hostname;
echo -e "\n${txtgrn}===============================";
echo -e "${txtgrn}macchanger\n${txtoc}";
ifconfig $interface down;
macchanger -a $interface;
ifconfig $interface up;
echo -e "\n${txtgrn}===============================";
echo -e "${txtgrn}systemctl start tor\n${txtoc}";
systemctl start tor;
systemctl status tor;
journalctl --rotate;
journalctl --vacuum-time=1s >/dev/null 2>&1;
echo -e "\n${txtgrn}===============================\n";
echo -e "${txtred}Don't forget to configure and use proxychains(4) properly!${txtoc}";
