#!/bin/bash

config_file=/etc/anon.conf

txtoc="\e[0m"; # oc
txtred="\e[31m"; # red
txtgrn="\e[38;2;0;230;153m"; # green


if test -f $config_file ; then
    . $config_file;
else
    echo -e "${txtred}Error: No config file found at $config_file \nModify ${txtoc}bash_blobs/anon_template.conf${txtred} and copy it in $config_file."
    exit 1
fi


echo -e "${txtgrn}===============================";
echo -e "${txtgrn}hostnamectl set-hostname\n${txtoc}";
hostnamectl set-hostname $new_hostname;
hostnamectl;
echo '';

echo -e "${txtgrn}===============================";
echo -e "${txtgrn}change_hostname.py\n${txtoc}";
change_hosts.py $new_hostname;

echo -e "\n${txtgrn}===============================";
echo -e "${txtgrn}macchanger\n${txtoc}";
ifconfig $interface down;
if [ -z ${specified_mac+x} ]; then
    macchanger -a $interface;
else
    macchanger --mac=$specified_mac $interface;
fi
ifconfig $interface up;

echo -e "\n${txtgrn}===============================";
echo -e "${txtgrn}systemctl start tor\n${txtoc}";
systemctl start tor;
systemctl status tor;
journalctl --rotate;
journalctl --vacuum-time=1s >/dev/null 2>&1;

echo -e "\n${txtgrn}===============================\n";
echo -e "${txtred}Don't forget to configure and use proxychains(4) properly!${txtoc}";
