#!/bin/bash

######### Configs #########
hostname='old-hostname';
interface='eth0';
####### End configs #######

txtoc="\e[0m"; # oc
txtred="\e[30m"; # red
txtgrn="\e[38;2;0;230;153m"; # green

systemctl stop tor;
echo -e "${txtgrn}===============================";
echo -e "${txtgrn}hostnamectl\n${txtoc}";
hostnamectl set-hostname $hostname;
hostnamectl;
echo '';
echo -e "${txtgrn}===============================";
echo -e "${txtgrn}change_hostname.py\n${txtoc}";
change_hosts.py $hostname;
echo -e "\n${txtgrn}===============================";
echo -e "${txtgrn}macchanger\n${txtoc}";
ifconfig $interface down;
macchanger -p $interface;
ifconfig $interface up;
echo -e "\n${txtgrn}===============================";
echo -e "${txtgrn}systemctl stop tor\n${txtoc}";
systemctl status tor;
journalctl --rotate;
journalctl --vacuum-time=1s > /dev/null 2>&1;
echo -e "\n${txtgrn}===============================\n";