#!/bin/bash

config_file=/etc/anon.conf

txtoc="\e[0m"; # oc
txtred="\e[31m"; # red
txtgrn="\e[38;2;0;230;153m"; # green


if test -f $config_file ; then
    . $config_file;
else
    echo -e "${txtred}Error: No config file found at $config_file \nModify ${txtoc}bash_blobs/anon_template.conf${txtred} and copy it in $config_file."
    exit 1
fi

systemctl stop tor;
echo -e "${txtgrn}===============================";
echo -e "${txtgrn}hostnamectl\n${txtoc}";
hostnamectl set-hostname $hostname;
hostnamectl;
echo '';
echo -e "${txtgrn}===============================";
echo -e "${txtgrn}change_hostname.py\n${txtoc}";
change_hosts.py $hostname;
echo -e "\n${txtgrn}===============================";
echo -e "${txtgrn}macchanger\n${txtoc}";
ifconfig $interface down;
macchanger -p $interface;
ifconfig $interface up;
echo -e "\n${txtgrn}===============================";
echo -e "${txtgrn}systemctl stop tor\n${txtoc}";
systemctl status tor;
journalctl --rotate;
journalctl --vacuum-time=1s > /dev/null 2>&1;
echo -e "\n${txtgrn}===============================\n";